### ISSUE TITLE
protocol sheet needs to be updated

### ISSUE THREAD

**Issue by mz973** [am4002/behav_trial#18]
-how participant is booked
-how time is reserved in the scanner
-how participant is prepared
- work out what documents to present to participants/operators/us

**Comment by daniel-pledger** [comment]
I seem to be unable to open the wiki from my laptop so not updated it over the weekend. Will make sure the bits that need to be changed are completed ahead of Alex coming in for behavioural training. 
_note to self_
Key points are check for flow and content listed above. I think the list of documents is complete

**Comment by daniel-pledger** [comment]
think this is ok now, managed to get this working. left 1 comment asking people to reread for sense. I will do this myself in YNIC tomorrow
