### ISSUE TITLE
add request: sequence checker functions

### ISSUE THREAD

**Issue by am4002** [am4002/behav_trial#2]
we require:
-sSeqChq(seq, %correct); takes one sequence and a target % correct, checks the sequence to make sure that it has enough potential correct matches to be within +/-10% of the target % correct. If there are too few or too many potential correct matches, the function randomly selects a number of trials and alters them to make them correct, then re-evaluates till the sequence is within acceptable parameters
-pSeqChq(seq1, seq2, %correct): the same as previous, but takes two sequences and evaluates them against each-other for correct matches

**Comment by mz973** [comment]
done!
